CREATE TABLE "ToDoUser" (
"UserId" SERIAL PRIMARY KEY,
"TelegramUserId" BIGINT NOT NULL,
"TelegramUserName" TEXT,
"RegisteredAt" TIMESTAMP NOT NULL DEFAULT NOW()
)
CREATE TABLE "ToDoList" (
"Id" SERIAL PRIMARY KEY,
"Name" TEXT NOT NULL,
"UserId" SERIAL NOT NULL REFERENCES "ToDoUser"("UserId") ON DELETE CASCADE,
"CreatedAt" TIMESTAMP NOT NULL DEFAULT NOW())

CREATE TABLE "ToDoItem" (
"Id" SERIAL PRIMARY KEY,
"UserId" SERIAL REFERENCES "ToDoUser" ("UserId")  ON DELETE CASCADE,
"Name" TEXT,
"CreatedAt" TIMESTAMP NOT NULL DEFAULT NOW(),
"State" INT NOT NULL DEFAULT 0,
"StateChangedAt" TIMESTAMP,
"Deadline" TIMESTAMP NOT NULL,
"ListId" SERIAL REFERENCES "ToDoList" ("Id") ON DELETE CASCADE )

CREATE UNIQUE INDEX "Ix_ToDoUser_TelegramUserId"
ON "ToDoUser"("TelegramUserId")

CREATE INDEX "Ix_ToDoItem_ListId" 
ON "ToDoItem"("ListId")

CREATE INDEX "Ix_ToDoItem_UserId" 
ON "ToDoItem"("UserId")